# Generated by Django 4.1.1 on 2022-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='isStockAvailable',
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(default=11, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stockAvailable',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=8),
        ),
    ]
