# Generated by Django 4.1.1 on 2022-09-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_is_available_product_isstockavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricePerQty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
