# Generated by Django 4.1.1 on 2022-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_priceperqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=32),
        ),
    ]
