# Generated by Django 4.1.1 on 2022-10-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image'),
        ('product', '0007_alter_product_category'),
    ]

    operations = [
    ]
