# Generated by Django 4.1.1 on 2022-11-02 04:33

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_merge_20221015_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='product/'),
        ),
    ]
