# Generated by Django 4.1.1 on 2022-11-21 07:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('transaction', '0001_initial'), ('transaction', '0002_alter_transaction_quantity'), ('transaction', '0003_alter_transaction_quantity'), ('transaction', '0004_alter_transaction_quantity'), ('transaction', '0005_remove_transaction_product_and_more'), ('transaction', '0006_remove_transactionproduct_product_and_more'), ('transaction', '0007_rename_productid_transactionproduct_product'), ('transaction', '0008_alter_transaction_products_and_more'), ('transaction', '0009_alter_transaction_products'), ('transaction', '0010_alter_transactionproduct_product'), ('transaction', '0011_alter_transaction_products'), ('transaction', '0012_alter_transactionproduct_product'), ('transaction', '0013_alter_transactionproduct_product'), ('transaction', '0014_alter_transactionproduct_product'), ('transaction', '0015_alter_transactionproduct_product'), ('transaction', '0016_rename_product_transactionproduct_product_id'), ('transaction', '0017_rename_product_id_transactionproduct_product'), ('transaction', '0018_rename_product_transactionproduct_product_id'), ('transaction', '0019_rename_product_id_transactionproduct_product'), ('transaction', '0020_alter_transactionproduct_product'), ('transaction', '0021_alter_transactionproduct_product_and_more'), ('transaction', '0022_alter_transactionproduct_product_and_more'), ('transaction', '0023_alter_transactionproduct_product_and_more'), ('transaction', '0024_alter_transactionproduct_product'), ('transaction', '0025_alter_transactionproduct_transaction'), ('transaction', '0026_alter_transactionproduct_transaction'), ('transaction', '0027_alter_transactionproduct_transaction'), ('transaction', '0028_transactionproduct_product_slug')]

    initial = True

    dependencies = [
        ('product', '0009_alter_product_image'),
        ('product', '0008_merge_20221015_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('namaPembeli', models.CharField(max_length=32)),
                ('nomorWhatsapp', models.CharField(max_length=16)),
                ('kabupaten', models.CharField(max_length=32)),
                ('kecamatan', models.CharField(max_length=32)),
                ('detailAlamat', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('pembayaran', models.CharField(max_length=32)),
                ('status', models.CharField(default='Belum Dibayar', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(through='transaction.TransactionProduct', to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionproduct',
            name='product_slug',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
