# Generated by Django 4.1.1 on 2022-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('kabupaten', models.CharField(max_length=32)),
                ('kecamatan', models.CharField(max_length=32)),
                ('addressDetail', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('whatsappNumber', models.CharField(max_length=16)),
                ('payment', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
