# Generated by Django 4.1.1 on 2022-11-07 07:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_merge_20221015_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('namaPembeli', models.CharField(max_length=32)),
                ('nomorWhatsapp', models.CharField(max_length=16)),
                ('kabupaten', models.CharField(max_length=32)),
                ('kecamatan', models.CharField(max_length=32)),
                ('detailAlamat', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('quantity', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), blank=True, null=True, size=None)),
                ('total', models.IntegerField()),
                ('pembayaran', models.CharField(max_length=32)),
                ('status', models.CharField(default='Belum Dibayar', max_length=32)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
