# Generated by Django 4.1.1 on 2022-11-07 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), blank=True, null=True, size=None),
        ),
    ]
