# Generated by Django 4.1.1 on 2022-11-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transactionproduct_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionproduct',
            old_name='productID',
            new_name='product',
        ),
    ]
