# Generated by Django 4.1.1 on 2022-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
        ('transaction', '0007_rename_productid_transactionproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(blank=True, through='transaction.TransactionProduct', to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
