# Generated by Django 4.1.1 on 2022-11-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
        ('transaction', '0010_alter_transactionproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(through='transaction.TransactionProduct', to='product.product'),
        ),
    ]
