# Generated by Django 4.1.1 on 2022-11-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_transactionproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionproduct',
            old_name='product',
            new_name='product_id',
        ),
    ]
