# Generated by Django 4.1.1 on 2022-11-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_rename_product_transactionproduct_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
