# Generated by Django 4.1.1 on 2022-11-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
        ('transaction', '0021_alter_transactionproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
            preserve_default=False,
        ),
    ]
