# Generated by Django 4.1.1 on 2022-11-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
        ('transaction', '0023_alter_transactionproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
