# Generated by Django 4.1.1 on 2022-11-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_alter_transactionproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
            preserve_default=False,
        ),
    ]
