# Generated by Django 4.1.1 on 2022-11-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0025_alter_transactionproduct_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduct',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
    ]
