# Generated by Django 4.1.1 on 2022-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0027_alter_transactionproduct_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionproduct',
            name='product_slug',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
