# Generated by Django 4.1.1 on 2022-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_squashed_0028_transactionproduct_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shiftPengantaran',
            field=models.CharField(default=-1.0, max_length=32),
            preserve_default=False,
        ),
    ]
