# Generated by Django 4.1.1 on 2022-12-16 13:08

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0029_transaction_shiftpengantaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buktiPembayaran',
            field=image_optimizer.fields.OptimizedImageField(blank=True, upload_to='transaction-evidence/'),
        ),
    ]
