# Generated by Django 4.1.1 on 2022-09-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
