# Generated by Django 4.1.1 on 2022-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sections', '0002_customsection_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsection',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
