# Generated by Django 4.1.1 on 2022-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sections', '0003_alter_customsection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsection',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
