# Generated by Django 4.1.1 on 2022-10-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banana',
        ),
    ]
