# Generated by Django 4.1 on 2022-11-21 11:23

import banner.models
from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(upload_to=banner.models.imageUploadHandler),
        ),
    ]
